### ISSUE TITLE
all the first column in gg.consensus is k__;p__;c__;o__;f__;g__;s__;

### ISSUE THREAD

**Issue by Tianjiao66** [thomasgurry/amplicon_sequencing_pipeline#3]
Dear author;
thanks for your pipline, but i have a problem about the closed reference based on GG database. all of the first column in gg.consensus is 'k__;p__;c__;o__;f__;g__;s__;',so i want to know how to get the right output. the denovo otu table and dbotu table is ok.
thanks.

**Comment by thomasgurry** [comment]
Thanks for reaching out.  Unfortunately, the GreenGenes part of the
pipeline was broken not long ago, and we are not entirely sure why.  If you
want to generate a closed reference table, you can do so by manually
mapping the *.dereplicated.fasta reads to GreenGenes using usearch and then
manually calling the relevant functions in preprocessing_16S.py to build
the table, but I think it would probably be quicker to generate a
closed-ref table using QIIME or QIIME2.  Personally I would recommend the
latter, as it is possible that the greengenes portion of the pipeline is
broken due to one of the aforementioned steps and you'll just end up having
to debug it.  Sorry for the inconvenience!!

**Comment by cduvallet** [comment]
I'll re-iterate what @thomasgurry said in that we highly recommend that you migrate to [QIIME 2](https://qiime2.org) - it's got all the same stuff we had here (including dbOTU), but much more robustly coded and with a large online support community! :) 

This pipeline code is no longer maintained or supported.

**Comment by Tianjiao66** [comment]
Thanks a lot. I still have a question, could you help me, please?
I want to use closed reference method to get otu, I try closed_ref command in usearch and pick_closed_reference_otus.py in qiime. But i can not get the representative sequence and i don't know how to get the taxonomy information for each otu. 
I will be very appreciate if you can help me.

**Comment by cduvallet** [comment]
Sorry, we don't provide this sort of support through this repo. You should check out the QIIME 2 forum - it's a great place to ask these sorts of questions! (And in fact, I'm pretty sure someone's already asked something similar).

Also, we'll just re-iterate that QIIME 2 (not QIIME 1) is really recommended for doing microbiome processing. It's fairly easy to get up-and-running, and has many useful features and a great supportive community on the forum.

QIIME 2: https://qiime2.org
Forum: https://forum.qiime2.org
